### ISSUE TITLE
IP address for DoH and DoT

### ISSUE THREAD

**Issue by chinmaythosar** [arapurayil/dns#7]
Is it possible for you to list IP addresses for manually configuring DoT and DoH for clients like stubby? I do not see any IPs anywhere or a 'contact us' either to obtain that.

**Comment by arapurayil** [comment]
I had listed that before but some mistook it for plaintext DNS@53 and so I took it down. 
Will put it up again when I redesign the site. 

IPv4: 3.7.176.123
IPv6: 2406:da1a:c59:ae00:20f:dbf5:a12c:5afb

**Comment by chinmaythosar** [comment]
Thank you. Yep makes sense.
